<?php
/**
 * Created by PhpStorm.
 * User: james
 * Date: 24/09/2013
 * Time: 14:59
 */

/**
 * Implements hook_menu().
 */
function db_prefixer_menu() {
  return array(
    'admin/config/db_prefixer' => array(
      'name' => t('DB Prefixer'),
      'description' => t('Select fields to be prefixed in settings'),
      'page callback' => 'db_prefixer_settings',
      'access callback' => TRUE,
    ),
  );
}


/**
 * Settings page callback.
 *
 * @return renderable form object
 */
function db_prefixer_settings() {
  return drupal_get_form('db_prefixer_form');
}


/**
 * Settings form.
 *
 * @param $form
 * @param $form_state
 * @return form array
 */
function db_prefixer_form($form, &$form_state) {

  global $databases;
  $default = $databases['default']['default']['database'];
  $query = db_query("SELECT table_name FROM INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA=:default", array(':default' => $default));
  $result = $query->fetchAll();

  $other_dbs = array(0 => 'default');
  foreach ($databases as $key => $database) {
    if ($key != 'default') {
      foreach ($database as $key => $db) {
        $other_dbs[$db['database']] = $db['database'];
      }
    }
  }

  $prefixed_tables = variable_get('db_prefixer_tables');
  $tables = $result;
  $form_state['tables'] = array();
  foreach($tables as $table) {
    $form[$table->table_name] = array(
      '#type' => 'select',
      '#title' => $table->table_name,
      '#options' => $other_dbs,
      '#default_value' => isset($prefixed_tables[$table->table_name]) ? $prefixed_tables[$table->table_name] : 0,
    );

    $form_state['tables'][] = $table->table_name;
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}


function db_prefixer_form_submit($form, $form_state) {
  $values = $form_state['values'];

  $prefixes = array();
  foreach ($form_state['tables'] as $table) {
    if (isset($values[$table]) && $values[$table] !== '0') {
      $prefixes[$table] = $values[$table];
    }
  }

  variable_set('db_prefixer_tables', $prefixes);
}


/**
 * Alter and return the array of fields which will be db_prefixed
 *
 * @param $prefix
 *   Array of tables and databases to be prefixed.
 */
function db_prefixer_tables(&$prefix = NULL, $databases = NULL) {

  $default = $databases['default']['default'];

  $link = mysql_connect($default['host'], $default['username'], $default['password']);
  if (!$link) {
    print 'error';
  }

  mysql_select_db($default['database']) or die(mysql_error());

  $sql="SELECT value FROM variable WHERE name = 'db_prefixer_tables'";

  // Execute query
  $result = mysql_query($sql);
  if (!$result) {
    die('Invalid query: ' . mysql_error());
  }

  mysql_close($link);

  $tables_ser = mysql_fetch_row($result);
  $tables = unserialize($tables_ser[0]);

  foreach ($tables as $table => $database) {
    $prefix[$table] = $database . '.';
  }
}